"""
Phase 1 — Synthetic Data Generator  (v2 — hard 150K 3-class)
=============================================================
Generates labeled time series for three bifurcation classes:
  0 — Saddle-node:    dx/dt = mu + x^2   (+higher order), mu swept through fold.
                      Parameter sweeps from stable regime to past the bifurcation →
                      critical slowing down (rising variance/AC) then rapid escape.
  1 — Transcritical:  dx/dt = mu*x - x^2 (+higher order), mu in bifurcating regime.
                      System starts near x=0 (unstable FP) and rises to saturation.
  2 — Null (Option C): 0→1 rising trajectory generated by a constant-parameter
                      NON-BIFURCATING ODE.  Three sub-types (equal probability):
                        A. Exponential saturation: dx/dt = r*(1-x)
                           Shape: concave-down, no inflection.
                        B. Linear ramp:            dx/dt = c (constant drift)
                           Shape: straight-line rise.  Zero curvature everywhere.
                        C. Partial expsat:         dx/dt = r*(x_sat - x), x_sat∈[0.25,0.75]
                           Shape: concave-down (same as A after normalization), but
                           represents niche adoption that stalls at partial penetration.

  INFLECTION POSITION DESIGN (v2):
  ─────────────────────────────────────────────────────────────────────────────
  v1 had TC inflection locked at exactly x≈0.50 (quadratic symmetry, a3≈0).
  v2 expands a3 range for TC and extends SN speed range downward, creating
  genuine overlap in the inflection-position feature dimension:

    TC  (v2):  a3 ∈ (-0.5, 0.5)  →  inflection ∈ [0.40, 0.62]
               Validation: inflection_position(x_500) < 0.65 (else retry)
    SN  (v2):  speed ∈ (0.3, 5.0) →  inflection ∈ [0.52, 0.85]
               Validation: inflection_position(x_500) > 0.50 (else retry)
    Overlap:   [0.52, 0.62]

  In the overlap region shape alone cannot discriminate SN from TC.  The model
  must learn CSD statistics (rising variance / rising AC during the pre-inflection
  phase for SN; flat statistics for TC).

  NOISE (v2 hard variant):
  ─────────────────────────────────────────────────────────────────────────────
  noise_levels extended to [0.005, 0.01, 0.02, 0.05, 0.10, 0.15, 0.20].
  phi_ar (AR(1) noise colour): SN/TC sampled from [0.0, 0.9]; Null from [0.0, 0.7].

  NULL CLASS HISTORY:
  ─────────────────────────────────────────────────────────────────────────────
  Option A (original): flat equilibrium fluctuations — trivially distinguishable
    by shape ("not rising → null"); model learned speed-based discrimination.
  Option B: expsat + Gompertz + Richards — Gompertz (inflection x≈0.37) and
    Richards (inflection x≈0.09–0.38) retired 2026-05-05 because their inflection
    points fall directly in SN feature-space territory, blurring the SN centroid.
  Option C (current): expsat + linear_ramp + partial_expsat.
    All three have no inflection in the SN/TC zone (x∈[0.40,0.62]).
    Teaches the model that the ABSENCE of a correctly-positioned S-curve inflection
    combined with flat CSD statistics → inconclusive.

Each sample is PCHIP-interpolated to exactly TARGET_POINTS = 500 uniform
grid points — identical to the real-world curation pipeline.

Default dataset: 150,000 samples (50,000 per class).
  → data/synthetic_150k_3class/X_full.npy   (150000, 500) float32
  → data/synthetic_150k_3class/y.npy         labels (0/1/2)
  → data/synthetic_150k_3class/metadata.json
  → data/synthetic_150k_3class/synthetic_dataset.pkl

Stage-1 centroid init uses 2-class subset: filter y < 2  →  100K (SN+TC only).

Usage:
    python Synthetic_Data_Gen.py                    # generates 150K to default path
    python Synthetic_Data_Gen.py --n 30000          # smaller run for testing
    python Synthetic_Data_Gen.py --out data/custom/ # custom output path

    from Synthetic_Data_Gen import SyntheticBifurcationDataset
    dataset = SyntheticBifurcationDataset(n_samples=150_000)
    dataset.generate()
    dataset.save("data/synthetic_150k_3class/")
"""

import argparse
import json
import os
import pickle
import warnings
from dataclasses import dataclass
from typing import Optional

import numpy as np

warnings.filterwarnings("ignore")

TARGET_POINTS = 500   # must match Real_World_Curator.TARGET_POINTS


# ─────────────────────────────────────────────
# 1. Data structures
# ─────────────────────────────────────────────

@dataclass
class SyntheticSample:
    label:        int          # 0=saddle-node, 1=transcritical, 2=null
    label_name:   str
    params:       dict         # ground-truth ODE parameters
    t:            np.ndarray   # raw integration time array (variable length)
    x_raw:        np.ndarray   # raw normalised series before PCHIP (variable length)
    x_full:       np.ndarray   # (TARGET_POINTS,) PCHIP-interpolated series
    noise_level:  float
    n_raw:        int          # number of raw integration steps


LABEL_NAMES = {0: "saddle_node", 1: "transcritical", 2: "null"}


# ─────────────────────────────────────────────
# 2. ODE right-hand sides
# ─────────────────────────────────────────────

# ── Bifurcating ODEs (SN and TC) ──────────────────────────────────────────────

def saddle_node_rhs(x, t, mu, a2=1.0, a3=0.0):
    """
    Saddle-node normal form: dx/dt = mu + a2*x^2 + a3*x^3
    Used with a mu_sweep so the parameter crosses the fold during the simulation.
    """
    return mu + a2 * x**2 + a3 * x**3


def transcritical_rhs(x, t, mu, a2=1.0, a3=0.0):
    """
    Transcritical normal form: dx/dt = mu*x - a2*x^2 + a3*x^3
    Exchange of stability at x=0 when mu crosses 0.  Fixed mu > 0 gives clean
    logistic rise from x≈0 to x=mu/a2 with an S-curve inflection at x≈mu/(2*a2).

    v2: a3 range extended to (-0.5, 0.5) to shift inflection from locked x≈0.50
    to a range [0.40, 0.62], creating genuine TC/SN overlap in inflection space.
    Validation in _generate_one rejects samples with inflection ≥ 0.65.
    """
    return mu * x - a2 * x**2 + a3 * x**3


# ── Null ODEs (Option C) — 0→1 rising, NO bifurcation, NO CSD ────────────────

def null_expsat_rhs(x, t, r):
    """
    Exponential saturation: dx/dt = r*(1-x).
    Stable FP at x=1.  Solution: x(t) = 1 - (1-x0)*exp(-r*t).
    Shape: CONCAVE-DOWN — derivative maximal at t=0, decays monotonically.
    No inflection point.  Eigenvalue at attractor = -r (constant → no CSD).
    r ∈ [0.5, 3.0].
    """
    return r * (1.0 - x)


def null_linear_ramp_rhs(x, t, c):
    """
    Linear ramp + hard plateau: dx/dt = c  while x < 1, else 0.
    Trajectory rises at constant rate c from x0 until x=1, then flat.
    No fixed point during rise, no eigenvalue → ZERO CSD by construction.
    Shape: straight-line rise followed by a plateau.
    c chosen so plateau starts at ~25–67% of t_end → plateau check always passes.
    """
    return float(c) if float(x) < 1.0 else 0.0


def null_partial_expsat_rhs(x, t, r, x_sat):
    """
    Partial exponential saturation: dx/dt = r*(x_sat - x), x_sat ∈ [0.25, 0.75].
    Stable FP at x = x_sat (niche adoption stall below full market penetration).
    After min-max normalization to [0,1]: shape is concave-down, identical in
    form to full expsat — the normalization maps x_sat → 1.0.
    Eigenvalue = -r (constant → no CSD).
    Represents technologies that capture partial market share and stall.
    r ∈ [0.5, 3.0], x_sat ∈ [0.25, 0.75].
    """
    return r * (float(x_sat) - float(x))


def null_sigmoid_template(rng, n_steps, t_end=None):
    """
    Deterministic generalized-logistic ('Richards') sigmoid whose inflection TIME
    is drawn anywhere in [0, 1], used as a NULL (no bifurcation).  Returned as a
    precomputed trajectory; the caller adds STATIONARY, constant-variance noise, so
    there is NO critical slowing down (variance / autocorrelation do not rise toward
    the takeoff) even though the curve has an S-shaped inflection that can coincide
    with the SN or TC inflection.  This removes inflection position/timing as a class
    cue, forcing any null-vs-bifurcation separation to rely on the noise dynamics.

    Returns x_det (length n_steps), rising from ~0 to ~1.
    """
    tau   = np.linspace(0.0, 1.0, n_steps)
    t_inf = rng.uniform(0.08, 0.80)            # inflection TIME (kept < 0.8 so it can plateau)
    k     = rng.uniform(8.0, 26.0)             # steepness
    nu    = rng.uniform(0.4, 2.5)              # asymmetry (nu != 1 => not the TC normal form)
    x = (1.0 / (1.0 + np.exp(-k * (tau - t_inf)))) ** nu
    x = x - x.min()
    return x / (x.max() + 1e-12)


# ── Archived null subtypes (retired 2026-05-05) ───────────────────────────────
# Gompertz and Richards were retired because their inflection points (x≈0.37 and
# x≈0.09–0.38 respectively) fall directly in SN feature-space territory, causing
# the unsupervised clusterer to confuse null with SN and blurring the SN centroid.
#
# def null_gompertz_rhs(x, t, r):   # inflection @ x≈0.37 → overlaps SN
#     x_safe = max(float(x), 1e-10)
#     return -r * x_safe * np.log(x_safe)
#
# def null_richards_rhs(x, t, r, alpha):  # inflection @ x≈0.09–0.38 → overlaps SN
#     x_safe = max(float(x), 1e-10)
#     return r * (x_safe ** alpha) * (1.0 - x_safe)


# ─────────────────────────────────────────────
# 3. Euler-Maruyama SDE integrator
# ─────────────────────────────────────────────

def integrate_sde(rhs, x0, t, params, sigma, rng, phi_ar=0.0, mu_sweep=None):
    """
    Euler-Maruyama integration of dx = f(x,t,params)dt + sigma*dW.
    Returns trajectory array of length len(t).
    Clips to [-10, 10] to avoid blow-up.

    Parameters
    ----------
    phi_ar   : AR(1) correlation coefficient (0 = white noise).
               Noise is η[i] = phi_ar*η[i-1] + ε[i], ε ~ N(0,1).
               noise_term = sigma * η[i] * sqrt(|dt|).
    mu_sweep : optional array of length len(t); if provided, overrides
               params['mu'] at each step i with mu_sweep[i].
    """
    dt = np.diff(t)
    x  = np.zeros(len(t))
    x[0] = x0
    eta = 0.0   # AR(1) state
    for i, dti in enumerate(dt):
        eps = rng.normal(0.0, 1.0)
        eta = phi_ar * eta + eps
        noise_term = sigma * eta * np.sqrt(abs(dti))
        step_params = dict(params)
        if mu_sweep is not None:
            step_params['mu'] = mu_sweep[i]
        x[i+1] = x[i] + rhs(x[i], t[i], **step_params) * dti + noise_term
        x[i+1] = np.clip(x[i+1], -10, 10)
    return x


# ─────────────────────────────────────────────
# 4. Per-class trajectory samplers
# ─────────────────────────────────────────────

def sample_saddle_node(rng, n_steps, t_end):
    """
    Saddle-node with linear parameter sweep through the fold (Bury et al. 2021).

    mu sweeps from mu_pre (before fold, two real FPs) to mu_post (past fold,
    FPs annihilated).  The system starts on the stable branch, shows CSD
    (rising variance and autocorrelation) as mu→0, then escapes rapidly.

    Shape: RIGHT-SKEWED — long quiet approach followed by sudden rapid jump.

    v2 change: speed lower bound lowered from 0.5 to 0.3.
    This allows fast-sweeping SN series where the fold is crossed quickly,
    pushing the normalised inflection down to x≈0.52–0.60 (overlap with TC).
    Validation in _generate_one rejects samples with inflection ≤ 0.50.
    Typical inflection range after change: [0.52, 0.85].
    """
    r        = rng.uniform(0.05, 0.35)
    a3       = rng.uniform(-0.05, 0.05)
    speed    = rng.uniform(0.3, 5.0)            # v2: lower bound 0.5 → 0.3
    mu_pre   = -speed * (r ** 2)
    mu_post  = r ** 2
    mu_sweep = np.linspace(mu_pre, mu_post, n_steps)
    x0       = -np.sqrt(abs(mu_pre)) * rng.uniform(0.90, 1.10)
    x_ref    = r
    params   = {"a2": 1.0, "a3": a3}
    return params, x0, x_ref, mu_sweep


def sample_transcritical(rng, n_steps, t_end):
    """
    Transcritical with fixed mu > 0.  System starts near x=0 (unstable FP)
    and rises smoothly to the stable FP at x = mu/a2.

    Shape: SIGMOID — S-curve with inflection at x ≈ mu/(2*a2).

    v2 change: a3 range expanded from (-0.1, 0.1) to (-0.5, 0.5).
    This shifts the inflection away from the locked x≈0.50 position:
      a3 < 0  →  inflection at x ≈ 0.40–0.48  (left-leaning sigmoid)
      a3 > 0  →  inflection at x ≈ 0.52–0.62  (right-leaning sigmoid)
    Validation in _generate_one rejects samples with inflection ≥ 0.65.
    Typical inflection range after change: [0.40, 0.62].
    """
    mu = rng.uniform(0.3, 4.0)
    a2 = rng.uniform(0.8, 2.0)
    a3 = rng.uniform(-0.5, 0.5)               # v2: range (-0.1,0.1) → (-0.5,0.5)
    x_stable = mu / a2
    x0 = rng.uniform(0.005, 0.05)
    params = {"mu": mu, "a2": a2, "a3": a3}
    return params, x0, x_stable, None


def sample_null_v2(rng, n_steps, t_end):
    """
    Null class: genuine 0→1 rising trajectory with ZERO critical slowing down.
    Three sub-types (equal probability 1/3 each):

    A. Linear ramp  dx/dt = c  (constant drift, x-independent).  Zero curvature.

    B. Partial expsat  dx/dt = r*(x_sat - x),  x_sat ∈ [0.25, 0.75].  Concave-down;
       niche adoption that stalls at partial penetration.  Eigenvalue = -r (constant).

    C. Sigmoid template (null_sigmoid_template): a generalized-logistic S-curve whose
       INFLECTION TIME is placed freely in [0, 1].  Returned as a precomputed trajectory
       (6th return value x_det); the caller adds STATIONARY, constant-variance AR(1)
       noise, so there is no critical slowing down even though the curve has an
       S-inflection that may coincide with the SN/TC inflection.  This removes curve
       shape/inflection as a class cue (null overlaps SN and TC in inflection), forcing
       any null-vs-bifurcation separation to rely on the noise dynamics.

    Returns
    -------
    rhs_fn      : callable | None   (None for the sigmoid template)
    params      : dict
    x0          : float
    x_ref       : float
    subtype     : str
    x_det       : np.ndarray | None  (precomputed trajectory for the sigmoid template)
    """
    # NEW null: linear-ramp + partial-expsat + a sigmoid template whose inflection
    # TIME can be anywhere in [0,1].  6th return value x_det is the precomputed
    # template trajectory (None for the ODE sub-types).
    subtype = rng.choice(["linear_ramp", "partial_expsat", "sigmoid"])

    if subtype == "linear_ramp":
        c  = rng.uniform(1.5, 4.0) / t_end
        x0 = rng.uniform(0.002, 0.02)
        return null_linear_ramp_rhs, {"c": c}, x0, 1.0, subtype, None

    elif subtype == "partial_expsat":
        x_sat = rng.uniform(0.25, 0.75)
        r     = rng.uniform(0.5, 3.0)
        x0    = rng.uniform(0.002, min(0.03, x_sat * 0.3))
        return null_partial_expsat_rhs, {"r": r, "x_sat": x_sat}, x0, x_sat, subtype, None

    else:  # sigmoid template, inflection time anywhere in [0,1]
        x_det = null_sigmoid_template(rng, n_steps, t_end)
        return None, {}, float(x_det[0]), 1.0, subtype, x_det


# ─────────────────────────────────────────────
# 5. Normalisation and PCHIP interpolation to TARGET_POINTS
# ─────────────────────────────────────────────

def normalize_series(x):
    """Min-max normalize to [0,1]. If flat, return zeros."""
    xmin, xmax = x.min(), x.max()
    if xmax - xmin < 1e-10:
        return np.zeros_like(x)
    return (x - xmin) / (xmax - xmin)


def pchip_to_500(x: np.ndarray, target: int = TARGET_POINTS) -> np.ndarray:
    """
    PCHIP-interpolate a normalised series to exactly `target` uniform points.
    Identical to Real_World_Curator.pchip_interpolate_to_target so that
    synthetic and real-world series go through the same resampling step.
    """
    from scipy.interpolate import PchipInterpolator

    n = len(x)
    if n == target:
        return x.astype(np.float32)

    t_orig = np.linspace(0.0, 1.0, n)
    t_new  = np.linspace(0.0, 1.0, target)

    interp = PchipInterpolator(t_orig, x, extrapolate=False)
    out    = interp(t_new)

    out[0]  = x[0]
    out[-1] = x[-1]
    nan_mask = np.isnan(out)
    if nan_mask.any():
        idx = np.arange(target)
        out[nan_mask] = np.interp(idx[nan_mask], idx[~nan_mask], out[~nan_mask])

    return np.clip(out, 0.0, 1.0).astype(np.float32)


def is_valid_trajectory(x, x_stable):
    """
    Reject trajectories that:
    - Blow up (max > 10)
    - Don't show meaningful range (< 0.05)
    - Contain NaN or Inf
    """
    if np.any(np.isnan(x)) or np.any(np.isinf(x)):
        return False
    if np.max(np.abs(x)) > 10:
        return False
    if x.max() - x.min() < 0.05:
        return False
    return True


def has_visible_plateau(x: np.ndarray, min_frac: float = 0.15, tol: float = 0.05) -> bool:
    """
    Check that the last `min_frac` fraction of the series has settled within
    `tol` (relative) of the global maximum.

    Applied to SN, TC, AND null (Option C) — all three classes produce 0→1
    rising curves that should saturate before the series ends.
    """
    n      = len(x)
    n_tail = max(3, int(n * min_frac))
    tail   = x[-n_tail:]
    xmax   = float(np.max(x))
    if xmax < 1e-8:
        return False
    return bool(np.all(np.abs(tail - xmax) / xmax <= tol))


def inflection_position(x: np.ndarray) -> float:
    """
    Estimate normalised position of the inflection point (max of dx/dt) in [0, 1].
    Returns position in [0, 1] where the growth rate peaks.
    """
    dx = np.diff(x)
    return float(np.argmax(dx)) / len(dx)


# ─────────────────────────────────────────────
# 6. Main dataset class
# ─────────────────────────────────────────────

class SyntheticBifurcationDataset:
    """
    Generates a balanced labeled dataset of bifurcation time series.
    Each series is PCHIP-interpolated to TARGET_POINTS (500) uniform points.

    v2 default: 150,000 samples (50,000 per class), hard noise variant.

    Parameters
    ----------
    n_samples : int
        Total number of samples (split equally across 3 classes).
        Default: 150,000  (50K SN + 50K TC + 50K Null).
    series_length_range : tuple
        (min, max) raw ODE integration steps.
    t_end_range : tuple
        (min, max) integration end time.
    noise_levels : list
        Sigma values to sample from for SDE noise.
        Default v2 (hard): [0.005, 0.01, 0.02, 0.05, 0.10, 0.15, 0.20].
    seed : int
        Random seed for reproducibility.
    """

    def __init__(
        self,
        n_samples:           int   = 150_000,
        series_length_range: tuple = (15, 80),
        t_end_range:         tuple = (5.0, 20.0),
        noise_levels:        list  = None,
        seed:                int   = 42,
    ):
        self.n_samples           = n_samples
        self.series_length_range = series_length_range
        self.t_end_range         = t_end_range
        # v2 hard variant: extended noise range
        self.noise_levels        = noise_levels or [0.005, 0.01, 0.02, 0.05,
                                                     0.10, 0.15, 0.20]
        self.seed                = seed
        self.rng                 = np.random.default_rng(seed)
        self.samples: list[SyntheticSample] = []

        self._rhs = {
            0: saddle_node_rhs,
            1: transcritical_rhs,
            2: None,   # determined dynamically by sample_null_v2
        }
        self._samplers = {
            0: sample_saddle_node,
            1: sample_transcritical,
            2: sample_null_v2,
        }

    def _generate_one(self, label: int, max_retries: int = 200) -> Optional[SyntheticSample]:
        sampler = self._samplers[label]

        for _ in range(max_retries):
            n_steps = int(self.rng.integers(*self.series_length_range))
            t_end   = self.rng.uniform(*self.t_end_range)
            t       = np.linspace(0, t_end, n_steps)

            sigma = self.rng.choice(self.noise_levels)

            # v2: harder AR noise for SN/TC; lighter for null
            # (real-world non-bifurcating series are less autocorrelated)
            phi_ar = (self.rng.uniform(0.0, 0.9) if label in (0, 1)
                      else self.rng.uniform(0.0, 0.7))

            x_det = None
            if label == 2:
                # Null: (rhs_fn, params, x0, x_ref, subtype, x_det); x_det set for the sigmoid template
                rhs_fn, params, x0, x_ref, null_subtype, x_det = sampler(self.rng, n_steps, t_end)
                mu_sweep   = None
                extra_meta = {"null_subtype": null_subtype}
            else:
                rhs_fn     = self._rhs[label]
                params, x0, x_ref, mu_sweep = sampler(self.rng, n_steps, t_end)
                extra_meta = {}

            if x_det is not None:
                # template null: deterministic sigmoid + STATIONARY AR(1) noise (constant
                # variance -> no critical slowing down), inflection time placed freely.
                eta = np.zeros(n_steps); e = self.rng.normal(0.0, 1.0, n_steps)
                for i in range(1, n_steps):
                    eta[i] = phi_ar * eta[i-1] + e[i]
                x = x_det + sigma * eta
            else:
                x = integrate_sde(rhs_fn, x0, t, params, sigma, self.rng,
                                   phi_ar=phi_ar, mu_sweep=mu_sweep)

            if not is_valid_trajectory(x, x_ref):
                continue

            # ── SN-specific validity: must escape past the fold ────────────
            if label == 0:
                if x.max() < 4.0:
                    continue

            x_norm = normalize_series(x)
            x_500  = pchip_to_500(x_norm)

            # ── Plateau check: ALL three classes must show saturation ───────
            if not has_visible_plateau(x_500):
                continue

            # ── v2: inflection position validation ─────────────────────────
            # Ensures TC and SN overlap at [0.52, 0.62] but not beyond:
            #   TC: reject if inflection ≥ 0.65 (would enter SN-only territory)
            #   SN: reject if inflection ≤ 0.50 (would be ambiguous with TC/null)
            # Null: no inflection check needed (expsat/linear_ramp/partial_expsat
            #       have no S-curve inflection — their "max dx" is at t=0).
            infl = inflection_position(x_500)
            if label == 1 and infl >= 0.65:
                continue
            if label == 0 and infl <= 0.50:
                continue

            full_params = {**params, **extra_meta}

            return SyntheticSample(
                label       = label,
                label_name  = LABEL_NAMES[label],
                params      = full_params,
                t           = t,
                x_raw       = x_norm,
                x_full      = x_500,
                noise_level = sigma,
                n_raw       = n_steps,
            )

        return None

    def generate(self, verbose: bool = True):
        """Generate n_samples balanced across 3 classes."""
        n_per_class = self.n_samples // 3
        counts = {0: 0, 1: 0, 2: 0}
        failed = 0

        if verbose:
            print(f"Generating {self.n_samples} samples ({n_per_class} per class)...")
            print(f"  noise_levels: {self.noise_levels}")
            print(f"  phi_ar: SN/TC=[0.0,0.9]  Null=[0.0,0.7]")

        for label in range(3):
            generated = 0
            attempts  = 0
            while generated < n_per_class:
                attempts += 1
                sample = self._generate_one(label)
                if sample is not None:
                    self.samples.append(sample)
                    generated += 1
                    counts[label] += 1
                    if verbose and generated % 5000 == 0:
                        print(f"    Class {label} ({LABEL_NAMES[label]}): "
                              f"{generated}/{n_per_class} …")
                else:
                    failed += 1
                if attempts > n_per_class * 30:
                    print(f"  Warning: too many retries for class {label}, "
                          f"stopping at {generated}")
                    break

            if verbose:
                reject_rate = 100.0 * (attempts - generated) / max(1, attempts)
                print(f"  Class {label} ({LABEL_NAMES[label]}): "
                      f"{generated} samples  "
                      f"(reject rate {reject_rate:.1f}%)")

        if verbose:
            print(f"\nTotal: {len(self.samples)} samples | "
                  f"Failed integrations / inflection rejects: {failed}")

    def get_arrays(self) -> tuple:
        """
        Return (X, y, params_list, lengths).

        Returns
        -------
        X           : (N, 500) float32  — PCHIP-interpolated normalised series
        y           : (N,)     int      — class labels (0=SN, 1=TC, 2=Null)
        params_list : list of dicts     — ground-truth ODE parameters
        lengths     : (N,)     int64    — all equal to TARGET_POINTS (500)
        """
        X       = np.stack([s.x_full for s in self.samples], axis=0).astype(np.float32)
        y       = np.array([s.label  for s in self.samples])
        params  = [s.params          for s in self.samples]
        lengths = np.full(len(self.samples), TARGET_POINTS, dtype=np.int64)
        return X, y, params, lengths

    def get_2class_arrays(self) -> tuple:
        """
        Return (X, y) for SN and TC only (exclude null, label 2).
        Used for Stage-1 centroid initialisation.

        Returns
        -------
        X2 : (N_sn + N_tc, 500) float32
        y2 : (N_sn + N_tc,)     int  — labels 0=SN, 1=TC
        """
        mask = np.array([s.label < 2 for s in self.samples])
        X_all, y_all, _, _ = self.get_arrays()
        return X_all[mask], y_all[mask]

    def summary(self):
        """Print dataset summary statistics."""
        if not self.samples:
            print("No samples generated yet.")
            return

        labels  = np.array([s.label       for s in self.samples])
        n_raws  = np.array([s.n_raw       for s in self.samples])
        noises  = np.array([s.noise_level for s in self.samples])

        # Inflection statistics per class
        inflections = np.array([inflection_position(s.x_full) for s in self.samples])

        print("=" * 65)
        print("Synthetic Dataset Summary  (v2 hard — Option C null)")
        print("=" * 65)
        print(f"Total samples        : {len(self.samples)}")
        for lbl, name in LABEL_NAMES.items():
            mask = labels == lbl
            if mask.sum() == 0:
                continue
            inf_med = np.median(inflections[mask])
            inf_p10 = np.percentile(inflections[mask], 10)
            inf_p90 = np.percentile(inflections[mask], 90)
            print(f"  {name:20s}: {mask.sum():6d}  "
                  f"inflection med={inf_med:.3f}  "
                  f"[p10={inf_p10:.3f}, p90={inf_p90:.3f}]")
        print(f"Output series length : {TARGET_POINTS} (fixed — PCHIP interpolation)")
        print(f"Raw integration pts  : min={n_raws.min()}, max={n_raws.max()}, "
              f"mean={n_raws.mean():.1f}")
        print(f"Noise levels         : {sorted(set(noises.tolist()))}")
        print(f"Noise mean/std       : {noises.mean():.4f} / {noises.std():.4f}")

        # Null sub-type breakdown
        null_subs = [s.params.get("null_subtype", "?")
                     for s in self.samples if s.label == 2]
        from collections import Counter
        print(f"  Null sub-types     : {dict(Counter(null_subs))}")

        # Overlap check: TC inflection range vs SN lower bound
        tc_mask = labels == 1; sn_mask = labels == 0
        tc_inf_max = np.percentile(inflections[tc_mask], 90)
        sn_inf_min = np.percentile(inflections[sn_mask], 10)
        print(f"\nInflection overlap check:")
        print(f"  TC  p90 inflection : {tc_inf_max:.3f}  (should be < 0.65)")
        print(f"  SN  p10 inflection : {sn_inf_min:.3f}  (should be > 0.50)")
        overlap = max(0.0, tc_inf_max - sn_inf_min)
        print(f"  Overlap band       : [{sn_inf_min:.3f}, {tc_inf_max:.3f}]  "
              f"width={overlap:.3f}")
        print("=" * 65)

    def save(self, output_dir: str):
        """Save dataset to output_dir."""
        os.makedirs(output_dir, exist_ok=True)

        with open(os.path.join(output_dir, "synthetic_dataset.pkl"), "wb") as f:
            pickle.dump(self.samples, f)

        X, y, _, lengths = self.get_arrays()
        np.save(os.path.join(output_dir, "X_full.npy"),  X)
        np.save(os.path.join(output_dir, "y.npy"),       y)
        np.save(os.path.join(output_dir, "lengths.npy"), lengths)

        # Save 2-class subset (SN+TC only) for Stage-1 centroid init
        X2, y2 = self.get_2class_arrays()
        np.save(os.path.join(output_dir, "X_2class.npy"), X2)
        np.save(os.path.join(output_dir, "y_2class.npy"), y2)

        labels = np.array([s.label for s in self.samples])
        meta = {
            "n_samples":            len(self.samples),
            "n_per_class":          {LABEL_NAMES[k]: int((labels==k).sum())
                                     for k in LABEL_NAMES},
            "n_2class_subset":      int((labels < 2).sum()),
            "null_class_version":   "option_c_v2",
            "null_subtypes":        ["expsat", "linear_ramp", "partial_expsat"],
            "target_points":        TARGET_POINTS,
            "series_length_range":  self.series_length_range,
            "t_end_range":          self.t_end_range,
            "noise_levels":         self.noise_levels,
            "phi_ar_sn_tc":         [0.0, 0.9],
            "phi_ar_null":          [0.0, 0.7],
            "tc_a3_range":          [-0.5, 0.5],
            "sn_speed_range":       [0.3, 5.0],
            "inflection_validation": {
                "TC": "< 0.65",
                "SN": "> 0.50",
                "overlap_target": "[0.52, 0.62]",
            },
            "seed":                 self.seed,
            "interpolation":        "PCHIP to 500 pts — same as real-world curator",
            "version":              "v2_hard_150k",
            "stage1_centroid_file": "X_2class.npy / y_2class.npy (SN+TC only)",
        }
        with open(os.path.join(output_dir, "metadata.json"), "w") as f:
            json.dump(meta, f, indent=2)

        print(f"\nDataset saved to: {output_dir}")
        print(f"  synthetic_dataset.pkl  — full Python objects")
        print(f"  X_full.npy             — ({len(self.samples)}, {TARGET_POINTS}) float32 [3-class]")
        print(f"  y.npy                  — labels 0/1/2")
        print(f"  X_2class.npy           — ({X2.shape[0]}, {TARGET_POINTS}) float32 [SN+TC only]")
        print(f"  y_2class.npy           — labels 0/1 [SN+TC only, for Stage-1 centroid init]")
        print(f"  lengths.npy            — all {TARGET_POINTS}")
        print(f"  metadata.json          — generation config")

    @classmethod
    def load(cls, output_dir: str) -> list:
        """Load samples from a saved dataset directory."""
        pkl_path = os.path.join(output_dir, "synthetic_dataset.pkl")
        with open(pkl_path, "rb") as f:
            samples = pickle.load(f)
        print(f"Loaded {len(samples)} samples from {output_dir}")
        return samples


# ─────────────────────────────────────────────
# 7. Quick visualisation (optional)
# ─────────────────────────────────────────────

def plot_samples(dataset: SyntheticBifurcationDataset, n_per_class: int = 5,
                 save_path: str = None):
    """
    Plot n_per_class example trajectories for each bifurcation class.
    Shows the 500-pt PCHIP series (solid) with the raw ODE trajectory
    overlaid as dots.  Also marks the inflection point position.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available — skipping plot.")
        return

    colors = {0: "#E63946", 1: "#2196F3", 2: "#4CAF50"}
    titles = {
        0: "Saddle-Node\n(inflection [0.52, 0.85])",
        1: "Transcritical\n(inflection [0.40, 0.62])",
        2: "Null — Option C\n(no S-curve inflection)",
    }

    fig, axes = plt.subplots(3, n_per_class, figsize=(3 * n_per_class, 9))
    fig.suptitle(
        f"Synthetic Dataset v2 (Option C null, hard variant) — {TARGET_POINTS}-pt PCHIP\n"
        "(solid = interpolated, dots = raw ODE, ▲ = inflection point)",
        fontsize=11, fontweight="bold",
    )

    for label in range(3):
        class_samples = [s for s in dataset.samples if s.label == label][:n_per_class]
        for j, s in enumerate(class_samples):
            ax     = axes[label][j]
            t_500  = np.linspace(0, 1, TARGET_POINTS)
            t_raw  = np.linspace(0, 1, len(s.x_raw))
            infl   = inflection_position(s.x_full)

            ax.plot(t_500, s.x_full, color=colors[label], lw=1.5)
            ax.plot(t_raw, s.x_raw,  ".", color="black", ms=2, alpha=0.4)
            ax.axvline(infl, color="gold", lw=1.0, ls="--", alpha=0.8)

            ax.set_ylim(-0.05, 1.1)
            ax.set_xlim(0, 1)
            ax.set_xticks([]); ax.set_yticks([])
            sub = s.params.get("null_subtype", "")
            if j == 0:
                ax.set_ylabel(titles[label], fontsize=8,
                              fontweight="bold", color=colors[label])
            if label == 0:
                ax.set_title(f"infl={infl:.2f}\nσ={s.noise_level}", fontsize=7)
            elif label == 1:
                ax.set_title(f"infl={infl:.2f}\na3={s.params.get('a3',0):.2f}", fontsize=7)
            elif label == 2:
                ax.set_title(f"{sub}\ninfl={infl:.2f}", fontsize=7)

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Plot saved to {save_path}")
    else:
        plt.show()


def plot_inflection_distributions(dataset: SyntheticBifurcationDataset,
                                   save_path: str = None):
    """
    Histogram of inflection positions per class.
    Shows the designed overlap region [0.52, 0.62] and validates
    that SN and TC do not fully separate in this feature dimension.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available — skipping plot.")
        return

    labels      = np.array([s.label for s in dataset.samples])
    inflections = np.array([inflection_position(s.x_full) for s in dataset.samples])

    colors = {0: "#E63946", 1: "#2196F3", 2: "#4CAF50"}
    names  = {0: "SN", 1: "TC", 2: "Null"}
    bins   = np.linspace(0.0, 1.0, 51)

    fig, ax = plt.subplots(figsize=(9, 4))
    for lbl in [0, 1, 2]:
        mask = labels == lbl
        ax.hist(inflections[mask], bins=bins, alpha=0.55,
                color=colors[lbl], label=f"{names[lbl]} (n={mask.sum():,})",
                density=True)

    ax.axvspan(0.52, 0.62, alpha=0.12, color="gold",
               label="Overlap zone [0.52, 0.62]")
    ax.axvline(0.50, color="gray",  ls="--", lw=1.2, alpha=0.7)
    ax.axvline(0.65, color="black", ls="--", lw=1.2, alpha=0.7,
               label="TC validation cutoff (0.65)")

    ax.set_xlabel("Normalised inflection position (x*)", fontsize=12)
    ax.set_ylabel("Density", fontsize=12)
    ax.set_title("Inflection Position Distributions — v2 Hard Synthetic Data",
                 fontsize=12, fontweight="bold")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Inflection distribution plot saved to {save_path}")
    else:
        plt.show()


# ─────────────────────────────────────────────
# 8. Entry point
# ─────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate hard 3-class synthetic bifurcation dataset (v2)."
    )
    parser.add_argument("--n",   type=int, default=150_000,
                        help="Total samples (default: 150000)")
    parser.add_argument("--out", type=str, default="data/synthetic_150k_3class",
                        help="Output directory")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed")
    parser.add_argument("--plot", action="store_true",
                        help="Generate example trajectory and inflection plots")
    args = parser.parse_args()

    print("=" * 65)
    print(f"  Synthetic Data Generator v2 — hard 3-class")
    print(f"  n={args.n:,}  out={args.out}  seed={args.seed}")
    print("=" * 65)

    dataset = SyntheticBifurcationDataset(
        n_samples           = args.n,
        series_length_range = (15, 80),
        t_end_range         = (5.0, 20.0),
        noise_levels        = [0.005, 0.01, 0.02, 0.05, 0.10, 0.15, 0.20],
        seed                = args.seed,
    )

    dataset.generate(verbose=True)
    dataset.summary()
    dataset.save(args.out)

    if args.plot:
        plot_samples(dataset, n_per_class=5,
                     save_path=os.path.join(args.out, "example_trajectories.png"))
        plot_inflection_distributions(
            dataset,
            save_path=os.path.join(args.out, "inflection_distributions.png"))
